name: dotnetcore build
on: push
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
      - run: dotnet --info
      - run: dotnet build --configuration Release
      - run: dotnet run --configuration Release --project ./MatrixBuildSandbox/
        env:
          DOTNET_ROOT: /Users/runner/hostedtoolcache/dncs/3.0.100/x64/sdk
      - uses: actions/upload-artifact@master
        with:
          name: release-build
          path: ./MatrixBuildSandbox/bin/Release/netcoreapp3.0/
