name: dotnetcore build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
      - run: dotnet --info
      - run: echo $DOTNET_ROOT
      - run: dotnet build --configuration Release
#      - run: dotnet run --configuration Release --project ./MatrixBuildSandbox/
      - uses: actions/upload-artifact@master
        with:
          name: release-build
          path: ./MatrixBuildSandbox/bin/Release/netcoreapp3.0/
